name: Certain events testing
# can use multiple event types by getting them together in brackets: on: [push, workflow_dispatch]
on:
  pull_request:
    types: opened
  issues:
    types:
      - opened
  workflow_dispatch:
jobs:
  lint:
    runs-on: windows-latest
    steps:
      - name: Get the event
        run: echo "Here is an event ${{ github.event }}"
      - name: Get the code
        uses: actions/checkout@v6
      - name: Install nodejs
        uses: actions/setup-node@v6
      - name: Install deps
        run: npm i
      - name: Lint the project
        run: npm run lint
      - name: Test the project
        run: npm run test
      - name: Build the project
        run: npm run build
      - name: Bye message
        run: echo "All steps are executed - bye bye"
