name: Reusable deploy workflow
on:
  workflow_call:
    inputs:
      artifact-name:
        description: name of the deployed file
        required: false
        default: dist
        type: string
    secrets:
      some-secret:
        required: true
    outputs:
      result:
        description: The result of this reusable workflow
        value: ${{ jobs.deploy.outputs.deploy-outcome }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      deploy-outcome: ${{ steps.set-res-id.outputs.step-result }}
    steps:
      - name: Download files
        uses: actions/download-artifact@v6
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Happy end
        run: echo "Yeeeeeeeey ${{ secrets.some-secret }}"
      - name: Set result
        id: set-res-id
        run: echo "step-result=success" >> $GITHUB_OUTPUT
